import mongoose from "mongoose"

const doctorSchema=mongoose.Schema({
    email:{
        required:true,
        type:String,
        unique:true,
    },
    password:{
        required:true,
        type:String,
    },
    name:{
        required:true,
        type:String,
    },
    phone:{
        type:Number,
    },
    ticketPrice:{
        type:Number,
    },
    role:{
        type:String,
    },
    specialization:{
        type:String,
    },
    qualification:{
        type:String,
    },
    experiences:{
        type:Array,
    },
    bio:{
        type:String,
    },
    about:{
        type:String,
    },
    timeSlots:{
        type:Array,
    },
    reviews:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Review",
        }
    ],
    averageRating:{
        type:Number,
        default:0,
    },
    totalRating:{
        type:Number,
        default:0,
    },
    isApproved:{
        type:String,
        enum:["pending","approved","cancelled"],
        default:"pending",
    },
    appointment:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Appointment",
        }
    ],
})

export const  Doctor=mongoose.model("Doctor",doctorSchema);